### ISSUE TITLE
Installation typo and TypeScript error in @fp-ts/optic README

### ISSUE THREAD

**Issue by ninesunsabiu** [fp-ts/optic#42]
Thank you very much for the surprises brought to me by the fp-ts series, which has helped me grow a lot.   
Now I'm trying to use @effect/* and @fp-ts/optic. However, I've found two issues in the README.md, and I hope to get some answers.

First, in the "Getting started" section, the installation method mentioned `npm install @fp-ts/schema` may be a typo, and the correct one should be `npm install @fp-ts/optic`.

Second, the example code in the "Summary" section will result in a TypeScript error, which is quite serious. Specifically, it shows:  

<img width="1151" alt="image" src="https://github.com/fp-ts/optic/assets/19882837/f3ffd22c-4b68-4976-a11c-7d318cff98a0">

```
Types of property 'getOptic' are incompatible.
        Type '(GetWhole: Employee) => Either<readonly [never, Employee], Option<string>>' is not assignable to type '(GetWhole: Employee) => Either<readonly [Error, Employee], Option<unknown>>'.ts(2769)
```
Here is [minimal reproduction](https://github.com/ninesunsabiu/optic-reproducible-error)

However, I tried it in [TypeScript playground](https://shorturl.at/ehO38) and it works correctly.I am very confused.

<img width="785" alt="image" src="https://github.com/fp-ts/optic/assets/19882837/fbec102e-7360-4e26-a867-c88b145c2e8c">

Here is my environment:

- macOS 13.3.1 (a)
- VS Code 1.78.2
- TypeScript 5.0.4
- pnpm 7.16.1

**Comment by ninesunsabiu** [comment]
It seems like there's an incompatibility issue between the `Option` used in @effect/data, which is a dependency of @fp-ts/optic(^0.11.5), and the one used in my project's dependencies(^0.12.2).

<img width="1172" alt="image" src="https://github.com/fp-ts/optic/assets/19882837/05f53726-b4ec-4e8f-8e52-1d9482ecb24c">


- I downgraded the version of @effect/data in my project to ^0.11.5 and the error disappeared.
- I added a pnpm.overrides in my package.json file to set the version of @effect/data to 0.12.2 and it also works fine now.

**Comment by gcanti** [comment]
Yeah, the `@effect/data` dependency must be updated, working on it

**Comment by gcanti** [comment]
[v0.8.0](https://github.com/fp-ts/optic/releases/tag/v0.8.0) released

**Comment by ninesunsabiu** [comment]
> [v0.8.0](https://github.com/fp-ts/optic/releases/tag/v0.8.0) released

Wow, that was really efficient! I was planning on having a meal before submitting a PR.
